name: Python test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3  

    - name: Set up Python 3.10
      uses: actions/setup-python@v4  
      with:
        python-version: '3.10' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Example, install pytest or other testing libraries you use
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: pytest  

    - name: Set up Node.js
      uses: actions/setup-node@v3  
      with:
        node-version: '20.x'  

    
    - name: Execute Node.js script
      run: node your-script.js  
