name: test
run-name: ${{ github.actor }} is testing
on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
jobs:
    test:
        runs-on: ubuntu-latest
        steps: 
           - uses: actions/checkout@v3
           - uses: actions/setup-python@v4
             with:
                python-version: 3.10
           - run: python3 -m pip install --upgrade pip
           - run: python3 -m pip install pytest
           - run: pip install -r requirements.txt
           - run: python3 --version
           - run: pytest --version
           - run: pytest